name: Daily Proxy Update and Restart

on:
  schedule:
    - cron: '0 2 * * *' # Каждый день ровно в 02:00 UTC (это 5:00 утра по МСК)
  workflow_dispatch: # Оставляем кнопку для ручного запуска в любое время

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Run Scraper and Generate PAC
      run: python build_pac.py

    - name: Commit and Push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add proxy.pac
        git commit -m "Daily auto-update 5 AM" || exit 0
        git push
